apps/galeria/urls.py
from django.urls import path
from apps.galeria.views import index, imagem, buscar, nova_imagem, editar_imagem, deletar_imagem, filtro

urlpatterns = [
    path("", index, name="index"),
    path("imagem/<int:foto_id>", imagem, name="imagem"),
    path("buscar", buscar, name="buscar"),
    path("nova-imagem", nova_imagem, name="nova_imagem"),
    path("editar-imagem/<int:foto_id>", editar_imagem, name="editar_imagem"),
    path("deletar-imagem/<int:foto_id>", deletar_imagem, name="deletar_imagem"),
    path("filtro/<str:categoria>", filtro, name="filtro")
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('apps.galeria.urls')),
    path("", include('apps.usuarios.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/galeria/models.py
from typing import Any
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.
class Fotografia(models.Model):
    OPCOES_CATEGORIA = [("NEBULOSA", "Nebulosa"), 
                        ("ESTRELA", "Estrela"), 
                        ("GALÁXIA", "Galáxia"), 
                        ("PLANETA", "Planeta")]
    nome = models.CharField(max_length=100, null=False, blank=False)
    legenda = models.CharField(max_length=150, null=False, blank=False)
    categoria = models.CharField(max_length=100, choices=OPCOES_CATEGORIA, default="")
    descricao = models.TextField(null=False, blank=False)
    foto = models.ImageField(upload_to="fotos/%Y/%m/%d/", blank=True)
    publicada = models.BooleanField(default=True)
    data_fotografia = models.DateTimeField(default=datetime.now, blank=False)
    usuario = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        related_name="user"
    )

    def __str__(self):
        #return f"Fotografia [nome={self.nome}]"
        return self.nome
    

galeria/models.py
from typing import Any
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.
class Fotografia(models.Model):
    OPCOES_CATEGORIA = [("NEBULOSA", "Nebulosa"), 
                        ("ESTRELA", "Estrela"), 
                        ("GALÁXIA", "Galáxia"), 
                        ("PLANETA", "Planeta")]
    nome = models.CharField(max_length=100, null=False, blank=False)
    legenda = models.CharField(max_length=150, null=False, blank=False)
    categoria = models.CharField(max_length=100, choices=OPCOES_CATEGORIA, default="")
    descricao = models.TextField(null=False, blank=False)
    foto = models.ImageField(upload_to="fotos/%Y/%m/%d/", blank=True)
    publicada = models.BooleanField(default=False)
    data_fotografia = models.DateTimeField(default=datetime.now, blank=False)
    usuario = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        related_name="user"
    )

    def __str__(self):
        #return f"Fotografia [nome={self.nome}]"
        return self.nome
    

apps/galeria/forms.py
from django import forms

from apps.galeria.models import Fotografia

class FotografiaForms(forms.ModelForm):
    class Meta:
        model = Fotografia
        exclude =['publicada',]
        labels = {
            'descricao': 'Descrição',
            'data_fotografia': 'Data de registro',
            'usuario': 'Usuário'
        }

        widgets = {
            'nome': forms.TextInput(attrs={'class':'form-control'}),
            'legenda': forms.TextInput(attrs={'class':'form-control'}),
            'categoria': forms.Select(attrs={'class':'form-control'}),
            'descricao': forms.Textarea(attrs={'class':'form-control'}),
            'foto': forms.FileInput(attrs={'class':'form-control'}),
            'data_fotografia': forms.DateInput(
                format='%Y-%m-%d', #'%d/%m/%y', Aqui é importante colocar o formato assim para que o form venha preenchido com a data.
                attrs={
                    'type':'date',
                    'class':'form-control'
                }),
            'usuario': forms.Select(attrs={'class':'form-control'}),
        }

apps/galeria/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from apps.galeria.models import Fotografia
from apps.galeria.forms import FotografiaForms

def index(request):
    if not request.user.is_authenticated:
        messages.error(request, "Usuário não logado!")
        return redirect('login')
    
    fotografias = Fotografia.objects.order_by("-data_fotografia").filter(publicada=True)
    return render(request, "galeria/index.html", {"cards": fotografias})

def imagem(request, foto_id):
    fotografia = get_object_or_404(Fotografia, pk=foto_id)
    return render(request, "galeria/imagem.html", {"fotografia": fotografia})

def buscar(request):
    if not request.user.is_authenticated:
        messages.error(request, "Usuário não logado!")
        return redirect('login')

    fotografias = Fotografia.objects.order_by("-data_fotografia").filter(publicada=True)
    if "buscar" in request.GET:
        nome_a_buscar = request.GET['buscar']
        if nome_a_buscar:
            fotografias = fotografias.filter(nome__icontains=nome_a_buscar)
    return render(request, "galeria/index.html", {"cards": fotografias})


def nova_imagem(request):
    if not request.user.is_authenticated:
        messages.error(request, "Usuário não logado!")
        return redirect('login')

    form = FotografiaForms
    if request.method == 'POST':
        form = FotografiaForms(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Nova fotografia cadastrada!')
            return redirect('index')

    return render(request, "galeria/nova_imagem.html", {'form': form})

def editar_imagem(request, foto_id):
    fotografia = Fotografia.objects.get(id=foto_id)
    form = FotografiaForms(instance=fotografia)

    if request.method == 'POST':
        form = FotografiaForms(request.POST, request.FILES, instance=fotografia)
        if form.is_valid():
            form.save()
            messages.success(request, 'Fotografia editada com sucesso!')
            return redirect('index')        
    return render(request, "galeria/editar_imagem.html", {'form': form, 'foto_id': foto_id})

def deletar_imagem(request, foto_id):
    fotografia = Fotografia.objects.get(id=foto_id)
    fotografia.delete()
    messages.success(request, 'Deleção feita com sucesso!')
    return redirect('index')

def filtro(request, categoria):
    fotografias = Fotografia.objects.order_by("-data_fotografia").filter(publicada=True, categoria=categoria)

    return render(request, "galeria/index.html", {"cards": fotografias})

templates/galeria/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alura Space</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">    
    <link rel="stylesheet" href="{% static '/styles/style.css' %}">
    {% block header %}{% endblock %} 
</head>

<body>    
    <div class="pagina-inicial">
        {% include 'partials/_header.html' %}
        <main class="principal">
            {% include 'partials/_side-menu.html' %}     
            {% block content %}{% endblock %} 
        </main>
    </div>
    {% include 'partials/_footer.html' %}
</body>

</html>

templates/galeria/buscar.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}    

<section class="conteudo">
    <section class="banner">
        <img class="banner__imagem" src="{% static 'assets/imagens/Banner(2).png' %}" alt="banner Alura Space">
        <h1 class="banner__titulo"> A galeria mais completa de fotos do espaço!</h1>
    </section>
    <section class="tags">
        <p class="tags__titulo">Busque por tags:</p>
        <ul class="tags__lista">
            <li class="tags__tag">Nebulosa</li>
            <li class="tags__tag">Estrela</li>
            <li class="tags__tag">Galáxia</li>
            <li class="tags__tag">Planeta</li>
        </ul>
    </section>
    <section class="galeria">
        <div class="cards">
            <h2 class="cards__titulo">Navegue pela galeria</h2>
            <ul class="cards__lista">
                {% if cards %}
                {% for fotografia in cards %}
                <li class="card">
                    <a href="{% url 'imagem' fotografia.id %}">
                        {% if fotografia.foto == "" or fotografia.foto == null %}}
                            <img class="card__imagem" src="{% static 'assets/imagens/galeria/not-found.png' %}" alt="foto">
                        {% else %}
                            <img class="card__imagem" src="{{ fotografia.foto.url }}" alt="foto">
                        {% endif %}
                    </a>
                    <span class="card__tag">{{ fotografia.get_categoria_display }}</span>
                    <div class="card__info">
                        <p class="card__titulo">{{ fotografia.nome }}</p>
                        <div class="card__texto">
                            <p class="card__descricao">{{ fotografia.legenda }}</p>
                            <span>
                                <img src="{% static 'assets/ícones/1x/favorite_outline.png' %}" alt="ícone de coração">
                            </span>
                        </div>
                    </div>
                </li>
                {% endfor %}
                {% else %}
                <div class="imagem__texto">
                    <p>Fotografias não encontradas</p>
                </div>
                {% endif %}
            </ul>
        </div>
    </section>
</section>
{% endblock %}

templates/galeria/editar_imagem.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}  

<section class="galeria" style="margin-left: 5em">
    <form action="{% url 'editar_imagem' foto_id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row"> 
            {% for field in form.visible_fields %}
                <div class="col-12 col-lg-12" style="margin-bottom: 10px;">
                    <label for="{{field.id_for_label}}" style="color:#D9D9D9; margin-bottom: 5px;"><b>{{field.label}}</b></label>
                    {{ field }}
                </div>
            {% endfor %}                        
        </div>
        <div class="col-12 text-center">
            <button type="submit" class="btn btn-success col-12" style="padding: top 5px;">Editar nova fotografia</button>
        </div>
    </form>
</section>

{% endblock %}

templates/galeria/imagem.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}

<section class="conteudo">
    <section class="imagem">
        <div class="imagem__conteudo">
            {% if fotografia.foto == "" or fotografia.foto == null %}}
                <img class="imagem__imagem" src="{% static 'assets/imagens/galeria/not-found.png' %}">
            {% else %}
                <img class="imagem__imagem" src="{{ fotografia.foto.url }}">
            {% endif %}

            <div class="imagem__info">
                <div class="imagem__texto">
                    <p class="imagem__titulo">{{fotografia.nome}}</p>
                    <p class="imagem__descricao">{{fotografia.legenda}}</p>
                    <p class="imagem__texto">{{fotografia.descricao}}</p>
                </div>
                <div>
                    <a href="{% url 'editar_imagem' fotografia.id %}"><button class="btn btn-success col-12" style="padding: top 5px;">Editar</button></a>
                    <a href="{% url 'deletar_imagem' fotografia.id %}"><button class="btn btn-danger col-12" style="padding: top 5px;">Deletar</button></a>
                </div>
            </div>
        </div>
    </section>
</section>
{% endblock %}

templates/galeria/index.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}    

<section class="conteudo">
    <section class="banner">
        <img class="banner__imagem" src="{% static 'assets/imagens/Banner(2).png' %}" alt="banner Alura Space">
        <h1 class="banner__titulo"> A galeria mais completa de fotos do espaço!</h1>
    </section>
    <section class="tags">
        <p class="tags__titulo">Busque por tags:</p>
        <ul class="tags__lista">
            <li class="tags__tag"><a href="{% url 'filtro' 'NEBULOSA' %}" class="btn" style="color: #c9c9c9">Nebulosa</a></li>
            <li class="tags__tag"><a href="{% url 'filtro' 'ESTRELA' %}" class="btn" style="color: #c9c9c9">Estrela</a></li>
            <li class="tags__tag"><a href="{% url 'filtro' 'GALÁXIA' %}" class="btn" style="color: #c9c9c9">Galáxia</a></li>
            <li class="tags__tag"><a href="{% url 'filtro' 'PLANETA' %}" class="btn" style="color: #c9c9c9">Planeta</a></li>
        </ul>
    </section>
    <section class="galeria">
        <div class="cards">
            <h2 class="cards__titulo">Navegue pela galeria</h2>
            <ul class="cards__lista">
                {% if cards %}
                {% for fotografia in cards %}
                <li class="card">
                    <a href="{% url 'imagem' fotografia.id %}">
                        {% if fotografia.foto == "" or fotografia.foto == null %}}
                            <img class="card__imagem" src="{% static 'assets/imagens/galeria/not-found.png' %}" alt="foto">
                        {% else %}
                            <img class="card__imagem" src="{{ fotografia.foto.url }}" alt="foto">
                        {% endif %}
                    </a>
                    <span class="card__tag">{{ fotografia.get_categoria_display }}</span>
                    <div class="card__info">
                        <p class="card__titulo">{{ fotografia.nome }}</p>
                        <div class="card__texto">
                            <p class="card__descricao">{{ fotografia.legenda }}</p>
                            <span>
                                <img src="{% static 'assets/ícones/1x/favorite_outline.png' %}" alt="ícone de coração">
                            </span>
                        </div>
                    </div>
                </li>
                {% endfor %}
                {% else %}
                <div class="imagem__texto">
                    <p>Fotografias não encontradas</p>
                </div>
                {% endif %}
            </ul>
        </div>
    </section>
</section>
{% endblock %}

templates/galeria/nova_imagem.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}  

<section class="galeria" style="margin-left: 5em">
    <form action="{% url 'nova_imagem' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row"> 
            {% for field in form.visible_fields %}
                <div class="col-12 col-lg-12" style="margin-bottom: 10px;">
                    <label for="{{field.id_for_label}}" style="color:#D9D9D9; margin-bottom: 5px;"><b>{{field.label}}</b></label>
                    {{ field }}
                </div>
            {% endfor %}                        
        </div>
        <div class="col-12 text-center">
            <button type="submit" class="btn btn-success col-12" style="padding: top 5px;">Cadastrar nova fotografia</button>
        </div>
    </form>
</section>

{% endblock %}